services:
  - type: web
    name: school-api
    env: node
    region: singapore  # Choose a region closest to your users
    buildCommand: npm ci && npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: 'true'
      # Use the internal database URL provided by Render
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString
      # For backward compatibility, also set individual connection parameters
      - key: DB_HOST
        fromDatabase:
          name: school-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: school-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: school-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: school-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: school-db
          property: database

databases:
  - name: school-db
    databaseName: school_db
    user: school_user
    plan: free
